### ISSUE TITLE
S5 Max API closed since last update 

### ISSUE THREAD

**Issue by tabnul** [89jd/hass-roborock#16]
I cannot use the integration anymore since upgrading the firmware of the S5 Max to 02.14.64
Port 6668 is closed now, the only open port on the device is 58867, which i cannot use to connect to using the plugin.

Dont upgrade to this version! Anyone can confirm?

**Comment by tabnul** [comment]
it seems more strange things are happening
i downgraded the firmware, same ports open. 

after following the exact same procedure as earlier to get the devid and localkey (using the same instance of bluestack) , i only get a RR file, the TUYA files are empty.
the localkey inside is invalid (no hexadecimal value) and the devid is non existent.


it seems they are closing down the api and backdoors to get access. can anyone confirm?

**Comment by tabnul** [comment]
response roborock customer support, not sure its entirely valid / whether the support agent actually knows;

---
Hello Customer
Thank you for contacting us
Unfortunately we do not have a time frame as to if or when the tcp port will be back open.

**Comment by derSeddy** [comment]
I can confirm that with `02.14.64` my S5 max cannot be controlled anymore.

> i downgraded the firmware

How did you downgrade the firmware and to which firmware did you downgrade? 

> same ports open

Does that mean the same ports are open as before the downgrade or after the downgrade? Or in other words: Was Port `6668` open again after the downgrade?

**Comment by tabnul** [comment]
> I can confirm that with `02.14.64` my S5 max cannot be controlled anymore.
> 
> > i downgraded the firmware
> 
> How did you downgrade the firmware and to which firmware did you downgrade?
> 
If you do a firmware reset, it will downgrade to an older version. Dont know exactly which it was.

> > same ports open
> 
> Does that mean the same ports are open as before the downgrade or after the downgrade? Or in other words: Was Port `6668` open again after the downgrade?

No unfortunately not... after downgrade 2 things didnt work as before:
- Port not open
- Not writing devkey and localkey to tuya file , using the exact same version of roborock app where it did work before (using bluestacks)
  Only a localkey gets written to a rr* file.
Basically its this behaviour: https://github.com/89jd/hass-roborock/issues/6

**Comment by tabnul** [comment]
using miihome app now,with official integration and vacuum maps integration.

**Comment by derSeddy** [comment]
Please reopen the issue, as it is not fixed.  
It may never get fixed and others might move to another solution like you did, but for reference I think this issue should stay open such that new users can see that the integration is broken for recent firmwares.
