### ISSUE TITLE
Roborock not loaded

### ISSUE THREAD

**Issue by TheGabeMan** [89jd/hass-roborock#17]
Since the new 2021.6 of HA, I had an issue that Roborock integration would not be loaded.
I solved it by simply adding one line to the manifest.json file:

"version": "1.0",

So my manifest.json would now be:
`{
  "domain": "roborock",
  "name": "Roborock",
  "config_flow": true,
  "documentation": "https://www.google.com",
  "requirements": ["pyroborock==1.0.10"],
  "version": "1.0",
  "codeowners": ["@89jd"]
}`

(Can't get the formatting correct)

Then reboot

**Comment by 89jd** [comment]
Can you raise pr?

**Comment by TheGabeMan** [comment]
Not familiar with Github. Should I now first fork your code, change manifest, raise PR ?

**Comment by TheGabeMan** [comment]
Think I created a PR :-)

**Comment by 89jd** [comment]
Great

Merged!
