### ISSUE TITLE
Error While Setting Up Roborock Integration

### ISSUE THREAD

**Issue by kernelpanic85** [89jd/hass-roborock#21]
Hi all,

I followed the instructions to add the Roborock integration from HACS. I configured my device, but no entities show up and this is what I see in the HA logs:

`Error while setting up roborock platform for vacuum
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/roborock/vacuum.py", line 146, in async_setup_entry
    tuya_init(js_dir)
  File "/usr/local/lib/python3.9/site-packages/tuyapipc/__init__.py", line 106, in init
    Popen(['npm', 'install', 'tuyapi-ipc'], \
  File "/usr/local/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'npm'`

Can anyone help with this?  I am running the latest version of HA on HASSOS on a Raspberry Pi.

**Comment by ddmmcz** [comment]
Hi, I also have this problem on Home Assistant Supervised, I own a roborock s6 max in and I also encountered the same error. I haven't found a solution yet.

**Comment by tabnul** [comment]
Just remove your robot from the roborock app and use the mihome app. after this you can use the official miio integration and the xiaomi map integrations. This is a huge improvement. 
Also the app itself is nowadays equal to the roborock app on your phone..

**Comment by tabnul** [comment]
to be honest this project should be archived for this reason. it is obsolete really.

**Comment by ddmmcz** [comment]
I'm already testing your proposed solution, I just didn't want to lose the possibility of an s6 max camera, but there is probably no other option.

**Comment by kernelpanic85** [comment]
Does the Xiaomi app have feature parity with Roborock? Would my existing map and custom zones import over?

**Comment by tabnul** [comment]
> Does the Xiaomi app have feature parity with Roborock? Would my existing map and custom zones import over?

Features are equal. You do have to recreate your zones. You can also create them in HA and navigate using the map in HA 
For instance i have an automation that drives the robot to the garbage can after cleaning, instead of to the hone base.

**Comment by RossGGG** [comment]
> Features are equal. You do have to recreate your zones. You can also create them in HA and navigate using the map in HA
> For instance i have an automation that drives the robot to the garbage can after cleaning, instead of to the hone base.

I don't think they are equal.  I can't seem to pull up a live video feed from the vacuum within the mi Home app.

**Comment by robertoleonardo** [comment]
yea the features are not even close to equal. live camera viewing is the big one. but also the automation options in mihome are laughable compared to roborock. and the alexa/google home integrations for mihome are also light years behind the roborock integrations. it is 100% false that the features are now equal. not by a mile. i just got a s7 maxv and it's incredible but i am shocked to realize how much of a trade off im forced to make to get it working in home assistant. pretty crazy for a vacuum that is otherwise so much better than its competitors.

**Comment by kernelpanic85** [comment]
Closing this as there is now an official Roborock integration in HA
