### ISSUE TITLE
iOSbackup

### ISSUE THREAD

**Issue by djungelola** [89jd/hass-roborock#3]
Trying to get the devId and localKey from an iOS backup. Neither of them is found but i see other id's.
token = 96295c30f97a48b685e315bbexxxxxxx-4c33d1673d5842d34b91462e1840b13757xxxxxx, guess this is same as local key?
How does the devId look like in an Android? 

/Ola

**Comment by TheGabeMan** [comment]
My (modified) keys look like this:
"localKey":"78215e844dc09e53"
"devId":"bf943b226c5bc35b22mdko"

**Comment by djungelola** [comment]
> My (modified) keys look like this:
> "localKey":"78215e844dc09e53"
> "devId":"bf943b226c5bc35b22mdko"

Thanks, then i found them in the backup!

**Comment by lubbertkramer** [comment]
> > My (modified) keys look like this:
> > "localKey":"78215e844dc09e53"
> > "devId":"bf943b226c5bc35b22mdko"
> 
> Thanks, then i found them in the backup!

Under which fields and file did you find them?
